version: '3'
services:

  app:
    build:
      context: .
      dockerfile: app/Dockerfile
    image: streamingplus-app
    hostname: streamingplusapp
    restart: unless-stopped
    volumes:
      - ./www:/var/www
      - ./.env:/var/www/.env
      - ./src:/var/src
    depends_on:
      - db

  core:
    build:
      context: .
      dockerfile: core/Dockerfile
    image: streamingplus-core
    hostname: streamingpluscore
    restart: unless-stopped
    ports:
      - "${SP_CORE_PORT}:5092"
    volumes:
      - ./www:/var/www
      - ./src:/var/src
      - ./core:/var/core
    depends_on:
      - app

  nginx:
    image: nginx:latest
    restart: unless-stopped
    ports:
      - "${SP_WEBUI_PORT}:80"
    volumes:
      - ./src/default.conf:/etc/nginx/conf.d/default.conf
      - ./www:/var/www
    depends_on:
      - app

  db:
    image: mariadb:latest
    restart: unless-stopped
    hostname: streamingplusdb
    environment:
      MYSQL_DATABASE: "${SP_DB_DATABASE}"
      MYSQL_ROOT_PASSWORD: "${SP_DB_PASSWORD}"
    ports:
      - "${SP_DB_EXT_PORT}:3306"
    volumes:
      - ${SP_DATA_PATH}/db/:/var/lib/mysql

  media:
    image: lscr.io/linuxserver/jellyfin:latest
    restart: unless-stopped
    hostname: streamingplusmedia
    environment:
      - PUID=${SP_PUID}
      - PGID=${SP_PGID}
      - TZ=${SP_TIMEZONE}
      - JELLYFIN_PublishedServerUrl=${SP_PUBLIC_URL}
    volumes:
      - ${SP_DATA_PATH}/media/config:/config
      - ${SP_DATA_PATH}/media/data:/data
    ports:
      - ${SP_MEDIACENTER_PORT}:8096