version: '3'
services:
  streaming:
    build:
      context: .
      dockerfile: Dockerfile
    image: streamingplus-app
    hostname: streamingplusapp
    restart: unless-stopped
    environment:
      - PUID=1000
      - GUID=1000
      - TIMEZONE=Europe/Rome
    volumes:
      - ./www:/var/www          #Questo lo mappo solo per non buildare ogni volta
      - ./src:/var/src          #Questo lo mappo solo per non buildare ogni volta
      - ./data:/data
    ports:
      - "8096:8096"
      - "8095:8095"
      - "8099:3000"
      #devices:
      #- /dev/dri:/dev/dri