version: '3'
services:
  streaming:
    build:
      context: .
      dockerfile: Dockerfile
    image: streamingplus-app
    hostname: streamingplusapp
    restart: unless-stopped
    volumes:
      - ./www:/var/www          #Questo lo mappo solo per non buildare ogni volta
      - ./src:/var/src          #Questo lo mappo solo per non buildare ogni volta
      - ./data:/data
    ports:
      - "8095:8095"
      - "8097:8097"
    #devices:
      #- /dev/dri:/dev/dri